admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 9000

node:
  cluster: mycluster
  id: test-id

dynamic_resources:
  cds_config:
    api_config_source:
      api_type: GRPC
      transport_api_version: V2
      grpc_services:
        envoy_grpc:
          cluster_name: xds_cluster

static_resources:
  listeners:
    - name: listener_0

      address:
        socket_address: { address: 0.0.0.0, port_value: 10000 }

      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              config:
                stat_prefix: ingress_http
                codec_type: AUTO
                rds:
                  route_config_name: local_route
                  config_source:
                    api_config_source:
                      api_type: GRPC
                      transport_api_version: V2
                      grpc_services:
                        envoy_grpc:
                          cluster_name: xds_cluster
                # route_config:
                #   name: local_route
                #   virtual_hosts:
                #     - name: local_service
                #       domains: ["*"]
                #       routes:
                #         - match: { prefix: "/" }
                #           route: { cluster: service_backend }
                http_filters:
                  - name: envoy.filters.http.router

  clusters:
    - name: xds_cluster
      type: STATIC
      connect_timeout: 0.25s
      lb_policy: ROUND_ROBIN
      http2_protocol_options: {}
      upstream_connection_options:
        tcp_keepalive: {}
      load_assignment:
        cluster_name: xds_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 8080
